import React, { useState } from 'react';
import { Ic } from './icons.jsx';
import { Utils } from '../utils/helpers.js';
import { TInp } from './shared.jsx';

export const DataManagerView = ({ title, data=[], setData, fields, filename, toast, setConfirm, isLog }) => {
  const [ie, setIe] = useState({ id: null, val: {} });
  const [f, setF] = useState({});
  const startEdit = r => setIe({ id: r.id, val: { ...r } });
  const saveEdit = () => {
    if (!isLog) return toast('로그인 필요');
    const u = ie.val;
    if (fields.some(fd => fd.inlineEditable && !u[fd.key])) return toast('모든 필드를 입력하세요.');
    if (!u.id) u.id = `${title.includes('사용자')?'U':title.includes('품목')?'I':title.includes('거래처')?'S':'C'}${Date.now()}`;
    setData(u.id === ie.id ? data.map(d => d.id === u.id ? u : d) : [...data, u]);
    setIe({ id: null, val: {} }); toast('저장됨');
  };
  const del = id => { if (!isLog) return toast('로그인 필요'); setConfirm({ is: true, msg: '삭제하시겠습니까?', onC: () => { setData(data.filter(d => d.id !== id)); setConfirm({ is: false }); toast('삭제됨'); }, onX: () => setConfirm({ is: false }) }); };
  const getF = () => data.filter(d => Object.keys(f).every(k => !f[k] || String(d[k] || '').toLowerCase().includes(f[k].toLowerCase())));
  const fd = getF();

  return (
    <div className="space-y-6 w-full animate-fade-in flex flex-col h-full min-h-0"><div className="flex justify-between items-end mb-2 flex-none"><div><h2 className="text-2xl font-bold">{title} 관리</h2><p className="text-[11px] text-gray-500 mt-1">총 {data.length}건의 {title} 데이터가 등록되어 있습니다.</p></div><div className="flex gap-2"><button onClick={() => Utils.dlStyled(fields.filter(x => !x.hideInList), data, filename)} className="px-4 py-2 bg-green-50 text-green-700 border border-green-200 rounded-xl text-xs font-black hover:bg-green-100 transition-colors flex items-center gap-1 shadow-sm"><Ic.File size={16} /> 엑셀 다운로드</button></div></div>
      <div className="bg-white p-6 rounded-3xl border shadow-sm flex-1 flex flex-col min-h-0 overflow-hidden"><div className="w-full border rounded-2xl flex-1 overflow-hidden flex flex-col relative"><div className="overflow-y-auto flex-1 scrollbar-hide"><table className="w-full text-left text-[11px]"><thead className="bg-slate-100 sticky top-0 shadow-sm border-b z-10"><tr>{fields.filter(f => !f.hideInList).map(f => <th key={f.key} className="p-3 font-bold text-slate-600 break-keep">{f.label}</th>)}<th className="p-3 w-32 break-keep text-center bg-slate-200 text-slate-700 shadow-inner">관리 도구</th></tr><tr className="bg-white border-b">{fields.filter(x => !x.hideInList).map(x => <th key={x.key} className="p-1 px-2 border-r last:border-r-0"><TInp v={f[x.key]} setV={v => setF({ ...f, [x.key]: v })} ph={`${x.label} 검색`} cls="w-full text-[10px] py-1 border-dashed bg-slate-50 focus:bg-white" /></th>)}<th className="p-1 px-2 border-l bg-slate-50"></th></tr></thead><tbody>{ie.id === 'NEW' && (<tr className="bg-blue-50/50 border-b-2 border-blue-200 shadow-inner">{fields.filter(f => !f.hideInList).map(f => <td key={f.key} className="p-2 border-r border-blue-100 border-dashed">{f.inlineEditable ? (f.type === 'select' ? <select value={ie.val[f.key] || ''} onChange={e => setIe({ ...ie, val: { ...ie.val, [f.key]: e.target.value } })} className="w-full p-2 border border-blue-200 rounded-lg text-[11px] font-black outline-none focus:border-blue-500 bg-white"><option value="">선택</option>{f.options.map(o => <option key={o.value} value={o.value}>{o.label}</option>)}</select> : <TInp v={ie.val[f.key]} setV={v => setIe({ ...ie, val: { ...ie.val, [f.key]: v } })} type={f.type || 'text'} cls="w-full text-[11px] p-2 border-blue-200 focus:ring-2 focus:ring-blue-100 bg-white" />) : <span className="text-slate-400 font-bold px-2">자동생성</span>}</td>)}<td className="p-2 flex gap-1 justify-center bg-blue-100/30"><button onClick={saveEdit} className="flex-1 p-2 bg-blue-600 text-white rounded-lg hover:bg-blue-700 shadow-sm transition-colors" title="저장"><Ic.Chk size={16} className="mx-auto" /></button><button onClick={() => setIe({ id: null, val: {} })} className="flex-1 p-2 bg-white text-slate-500 border border-slate-200 rounded-lg hover:bg-slate-50 shadow-sm transition-colors" title="취소"><Ic.X size={16} className="mx-auto" /></button></td></tr>)}
        {fd.map(d => ie.id === d.id ? (<tr key={d.id} className="bg-yellow-50/50 border-b-2 border-yellow-200 shadow-inner">{fields.filter(f => !f.hideInList).map(f => <td key={f.key} className="p-2 border-r border-yellow-100 border-dashed">{f.inlineEditable ? (f.type === 'select' ? <select value={ie.val[f.key] || ''} onChange={e => setIe({ ...ie, val: { ...ie.val, [f.key]: e.target.value } })} className="w-full p-2 border border-yellow-300 rounded-lg text-[11px] font-black outline-none focus:border-yellow-500 bg-white"><option value="">선택</option>{f.options.map(o => <option key={o.value} value={o.value}>{o.label}</option>)}</select> : <TInp v={ie.val[f.key]} setV={v => setIe({ ...ie, val: { ...ie.val, [f.key]: v } })} type={f.type || 'text'} cls="w-full text-[11px] p-2 border-yellow-300 focus:ring-2 focus:ring-yellow-100 bg-white" />) : <span className="text-slate-600 font-bold px-2">{d[f.key]}</span>}</td>)}<td className="p-2 flex gap-1 justify-center bg-yellow-100/30"><button onClick={saveEdit} className="flex-1 p-2 bg-yellow-500 text-white rounded-lg hover:bg-yellow-600 shadow-sm transition-colors" title="수정 완료"><Ic.Chk size={16} className="mx-auto" /></button><button onClick={() => setIe({ id: null, val: {} })} className="flex-1 p-2 bg-white text-slate-500 border border-slate-200 rounded-lg hover:bg-slate-50 shadow-sm transition-colors" title="취소"><Ic.X size={16} className="mx-auto" /></button></td></tr>) : (<tr key={d.id} className="border-b hover:bg-slate-50 transition-colors group">{fields.filter(f => !f.hideInList).map(f => <td key={f.key} className="p-3 border-r border-slate-100 border-dashed font-black text-slate-700 break-words">{f.type === 'select' && f.options ? (f.options.find(o => o.value === d[f.key])?.label || d[f.key]) : (f.type === 'number' ? Utils.fmt(d[f.key]) : d[f.key])}</td>)}<td className="p-2 opacity-30 group-hover:opacity-100 transition-opacity bg-slate-50/50"><div className="flex gap-1 justify-center"><button onClick={() => startEdit(d)} className="p-2 bg-white border border-slate-200 rounded-lg text-slate-600 hover:text-blue-600 hover:border-blue-200 shadow-sm transition-colors" title="수정"><Ic.Edit size={14} /></button><button onClick={() => del(d.id)} className="p-2 bg-white border border-slate-200 rounded-lg text-slate-600 hover:text-rose-600 hover:border-rose-200 shadow-sm transition-colors" title="삭제"><Ic.Trash size={14} /></button></div></td></tr>))}
        {fd.length === 0 && ie.id !== 'NEW' && <tr><td colSpan={fields.length + 1} className="p-20 text-center font-bold text-slate-400 bg-slate-50/50">검색 결과 또는 등록된 데이터가 없습니다.</td></tr>}
      </tbody></table></div></div>
      <div className="flex justify-end mt-4"><button onClick={() => { if (!isLog) return toast('로그인 필요'); if (ie.id) return toast('수정 중인 항목을 먼저 완료하세요.'); setIe({ id: 'NEW', val: {} }); }} className="bg-slate-800 hover:bg-slate-900 text-white px-8 py-4 rounded-xl font-black shadow-md text-sm transition-transform hover:-translate-y-0.5 flex items-center gap-2"><Ic.Plus size={18} /> 신규 {title} 등록하기</button></div></div>
    </div>
  );
};
