import React, { useState, useMemo, useEffect } from 'react';
import { Ic } from './icons.jsx';
import { Utils } from '../utils/helpers.js';

export const PaymentView = ({ payments=[], setPayments, suppliers=[], purchaseRequests=[], toast, isLog, globalMonth }) => {
  const [vP, setVP] = useState(null), [sel, setSel] = useState([]); 
  const fd = useMemo(() => payments.filter(p => (p.date||'').startsWith(globalMonth)).sort((a,b)=>(b.date||'').localeCompare(a.date||'')), [payments, globalMonth]);
  useEffect(() => { setSel([]); }, [globalMonth]);

  const handlePrint = () => { let h = `<table border="1"><thead><tr><th colspan="4" style="font-size:16pt; background:#d9e1f2; padding:10px;">${globalMonth}월 대금 정산 내역</th></tr><tr><th>입고일</th><th>거래처</th><th>청구금액</th><th>상태</th></tr></thead><tbody>`; fd.forEach(p => { h += `<tr><td>${p.date}</td><td style="text-align:left;">${p.supplierName}</td><td style="text-align:right; font-weight:bold;">${Utils.fmt(p.amount)}</td><td style="color:${p.status==='paid'?'green':'red'}; font-weight:bold;">${p.status==='paid'?'결제완료':'미결제'}</td></tr>`; }); h += `</tbody></table>`; Utils.printContent(`${globalMonth}월 대금정산내역`, h); };
  const handleExcel = () => { const data = fd.map(p => ({ date: p.date, supplierName: p.supplierName, amount: p.amount, status: p.status==='paid'?'결제완료':'미결제' })); const fields = [{key:'date', label:'입고일'}, {key:'supplierName', label:'거래처'}, {key:'amount', label:'청구금액', type:'number'}, {key:'status', label:'상태'}]; Utils.dlStyled(fields, data, `대금정산내역_${globalMonth}`); };
  const handleDeleteSelected = () => { if(!isLog) return toast('로그인 필요'); if(!window.confirm(`선택한 대금정산 내역 ${sel.length}건을 삭제하시겠습니까?`)) return; setPayments(payments.filter(p => !sel.includes(p.id))); setSel([]); toast('선택한 결제 내역이 삭제되었습니다.'); };

  return (
    <div className="space-y-6 w-full animate-fade-in flex flex-col h-full min-h-0"><div className="flex justify-between items-end mb-2 flex-none"><div><h2 className="text-2xl font-bold">대금 정산</h2><p className="text-[11px] text-gray-500 mt-1">입고 완료된 건에 대해 결제 상태를 관리합니다.</p></div>
       <div className="flex gap-2 items-center">
          {isLog && sel.length > 0 && <button onClick={handleDeleteSelected} className="px-4 py-2 bg-red-50 text-red-600 border border-red-200 rounded-xl text-xs font-black hover:bg-red-100 transition-colors flex items-center gap-1"><Ic.Trash size={16}/> 선택 삭제 ({sel.length})</button>}
          <button onClick={handleExcel} className="px-4 py-2 bg-green-50 text-green-700 border border-green-200 rounded-xl text-xs font-black hover:bg-green-100 transition-colors flex items-center gap-1"><Ic.File size={16}/> 엑셀 다운로드</button>
          <button onClick={handlePrint} className="px-4 py-2 bg-gray-800 text-white rounded-xl text-xs font-black hover:bg-gray-900 transition-colors flex items-center gap-1"><Ic.Print size={16}/> 인쇄 미리보기</button>
       </div>
    </div>
      <div className="bg-white p-6 rounded-3xl border shadow-sm flex-1 flex flex-col min-h-0 overflow-hidden"><div className="w-full border rounded-2xl flex-1 overflow-y-auto scrollbar-hide"><table className="w-full text-[10px] text-center table-fixed"><thead className="bg-gray-100 sticky top-0 shadow-sm border-b z-10"><tr>{isLog&&<th className="p-3 w-10 break-keep"><input type="checkbox" onChange={e=>setSel(e.target.checked?fd.map(i=>i.id):[])} checked={fd.length>0&&sel.length===fd.length}/></th>}<th className="p-3 w-[15%] break-keep">입고일</th><th className="p-3 text-left w-[40%] break-keep">거래처</th><th className="p-3 text-right w-[15%] break-keep">청구금액</th><th className="p-3 w-[10%] break-keep">상태</th>{isLog&&<th className="p-3 w-[10%] break-keep">처리</th>}</tr></thead><tbody>{fd.length===0?<tr><td colSpan={isLog?"6":"5"} className="p-20 font-bold text-gray-400">결제 내역 없음</td></tr>:fd.map(p=><tr key={p.id} className="border-b hover:bg-gray-50 cursor-pointer" onClick={()=>setVP(p)}>{isLog&&<td className="p-3" onClick={e=>e.stopPropagation()}><input type="checkbox" checked={sel.includes(p.id)} onChange={e=>{e.stopPropagation();setSel(prev=>e.target.checked?[...prev,p.id]:prev.filter(id=>id!==p.id));}}/></td>}<td className="p-3 font-bold text-gray-500 break-keep">{p.date}</td><td className="p-3 font-black text-left break-words">{p.supplierName || suppliers.find(x=>x.id===p.supplierId)?.name}</td><td className="p-3 font-black text-right break-keep">{Utils.fmt(p.amount)}</td><td className="p-3 break-keep"><span className={`px-2 py-1 rounded text-[10px] font-black ${p.status==='paid'?'bg-green-100 text-green-700':'bg-red-100 text-red-600'}`}>{p.status==='paid'?'결제완료':'미결제'}</span></td>{isLog&&<td className="p-3 break-keep"><button onClick={(e)=>{e.stopPropagation(); setPayments(payments.map(x=>x.id===p.id?{...x,status:x.status==='paid'?'unpaid':'paid'}:x)); toast('변경됨');}} className="border px-3 py-1 rounded text-[10px] font-black bg-white hover:bg-gray-50 transition-colors">{p.status==='paid'?'취소':'결제하기'}</button></td>}</tr>)}</tbody></table></div></div>
      
      {vP && (
        <div className="absolute inset-0 z-[9999] bg-slate-900/40 backdrop-blur-sm flex justify-center items-center p-4 sm:p-6 animate-fade-in notranslate" translate="no">
          <div className="bg-white flex flex-col w-full max-w-4xl mx-auto rounded-[2.5rem] shadow-[0_0_40px_rgba(0,0,0,0.1)] border border-slate-200 animate-scale-up h-[90vh]">
            <div className="flex-none px-8 py-6 border-b border-slate-100 flex justify-between items-center bg-white rounded-t-[2.5rem] pr-16"><h3 className="text-xl sm:text-2xl font-black text-slate-800 flex items-center gap-3"><Ic.Card size={28} className="text-purple-600"/> {vP.supplierName || suppliers.find(s=>s.id===vP.supplierId)?.name} 거래 상세 (청구금액: <span className="text-rose-500 ml-2">{Utils.fmt(vP.amount)}원</span>)</h3><button onClick={()=>setVP(null)} className="absolute top-6 right-6 p-2 bg-slate-100 rounded-full hover:text-rose-600 transition-colors"><Ic.X size={20}/></button></div>
            <div className="flex-1 p-4 sm:p-6 bg-slate-50 flex flex-col min-h-0"><div className="bg-white border border-slate-200 rounded-2xl shadow-sm flex flex-col flex-1 min-h-0 overflow-hidden"><div className="overflow-y-auto flex-1 w-full scrollbar-hide"><table className="w-full text-[10px] text-center table-fixed"><thead className="bg-slate-100 sticky top-0 shadow-sm border-b z-10"><tr><th className="p-3 border-r w-[45%] break-keep">품명</th><th className="p-3 bg-blue-50 text-blue-800 border-r w-[20%] break-keep">입고수량</th><th className="p-3 border-r w-[15%] break-keep">단가</th><th className="p-3 text-amber-600 w-[20%] break-keep">청구금액</th></tr></thead><tbody>{(purchaseRequests.find(r=>r.id===vP.prId)?.items||[]).map((it, idx) => (<tr key={`pay-det-${it.itemId}-${idx}`} className="border-b hover:bg-gray-50"><td className="p-3 font-black text-left border-r break-words">{it.name}</td><td className="p-3 font-black text-blue-700 bg-blue-50/20 text-lg border-r break-keep">{Utils.fmt(it.reqBoxes)}</td><td className="p-3 font-bold text-gray-600 border-r break-keep">{Utils.fmt(it.unitPrice)}</td><td className="p-3 font-black text-amber-600 break-keep">{Utils.fmt(it.reqBoxes * it.unitPrice)}</td></tr>))}</tbody></table></div></div></div>
            <div className="flex-none px-8 py-5 border-t border-slate-100 bg-white flex justify-end rounded-b-[2.5rem]"><button onClick={()=>{setPayments(payments.map(x=>x.id===vP.id?{...x,status:vP.status==='paid'?'unpaid':'paid'}:x)); setVP({...vP, status:vP.status==='paid'?'unpaid':'paid'}); toast('상태 변경됨');}} className={`px-12 py-4 rounded-xl font-black shadow-md text-base text-white transition-transform hover:-translate-y-0.5 ${vP.status==='paid'?'bg-gray-800 hover:bg-gray-900':'bg-purple-600 hover:bg-purple-700'}`}>{vP.status==='paid'?'결제 상태 취소로 변경':'대금 결제 승인 완료'}</button></div>
          </div>
        </div>
      )}
    </div>
  )
};
